apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-9
spec:
  replicas: 2
  selector:
    matchLabels:
      app: type-9
  template:
    metadata:
      labels:
        app: type-9
    spec:
      containers:
        - name: type-9
          image: docker.io/timattt/type-9:latest
          imagePullPolicy: Always
          env:
            - name: HTTPS
              value: "false"
